"""Crop the household photos into small square face JPEGs and inject them as
base64 data-URIs into soft-kids-game/index.html between the FACES markers.

`households/` is the source of truth for who exists:

    households/<Household>/<Kid>.jpg          a pickable kid
    households/<Household>/Parents/<Name>.jpg  a parent

Crop boxes are hand-picked fractions (left, top, right, bottom) of the
EXIF-corrected image, chosen by eye per photo. The script squares the box around
its center, crops, resizes to 176x176 and re-injects the whole FACES block, so it
is safe to re-run whenever photos or crops change.

Adding a kid: drop the photo in, add a FACE_CROPS line, re-run. The character
still needs a CHARACTERS spec and a HOUSEHOLDS entry in index.html — this script
fails loudly if a photo has no crop box, so a forgotten one cannot ship as a
silently mis-cropped face.
"""

import base64
import io
import re
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
HOUSEHOLDS = ROOT / "households"
INDEX = ROOT / "soft-kids-game" / "index.html"

SIZE = 176
QUALITY = 72

# character id -> (path relative to households/, (l, t, r, b) crop fractions)
FACE_CROPS = {
    # --- Eya's household
    "eya":           ("Eya/Eya.JPG",                          (0.305, 0.336, 0.611, 0.670)),
    "mommyKristine": ("Eya/Parents/Mommy Kristine.JPG",       (0.330, 0.330, 0.680, 0.720)),
    "daddyLaurence": ("Eya/Parents/Daddy Laurence.JPG",       (0.270, 0.150, 0.780, 0.700)),
    # --- Jeya's household
    "jeya":          ("Jeya/Jeya.jpg",                        (0.350, 0.385, 0.560, 0.520)),
    "nanayJessa":    ("Jeya/Parents/Nanay Jessa.jpg",         (0.510, 0.290, 0.750, 0.630)),
    "tatayJeff":     ("Jeya/Parents/Tatay Jeff.jpg",          (0.580, 0.160, 0.860, 0.330)),
    # --- Gab's household
    "gab":           ("Gab/Gab.jpg",                          (0.450, 0.200, 0.980, 0.560)),
    "mommyDanielle": ("Gab/Parents/Mommy Danielle.jpg",       (0.380, 0.270, 0.780, 0.660)),
    # --- Mommy Debs' household (two kids)
    "tia":           ("Tia or Timmy/Tia.jpg",                 (0.280, 0.220, 0.470, 0.370)),
    "timmy":         ("Tia or Timmy/Timmy.jpg",               (0.400, 0.070, 0.630, 0.290)),
    "mommyDebs":     ("Tia or Timmy/Parents/Mommy Debs.jpg",  (0.300, 0.250, 0.730, 0.710)),
    # --- Tito Boy (no kids, just a house). IMG_5170 is the only front-facing shot.
    "titoBoy":       ("Tito Boy/Tito Boy/IMG_5170.JPG",       (0.430, 0.340, 0.630, 0.500)),
}

BEGIN = "// ===== FACES:BEGIN (generated by tools/make_faces.py — do not edit by hand)"
END = "// ===== FACES:END"


def face_data_uri(path: Path, frac_box) -> str:
    img = Image.open(path)
    img = ImageOps.exif_transpose(img).convert("RGB")
    w, h = img.size
    l, t, r, b = (frac_box[0] * w, frac_box[1] * h, frac_box[2] * w, frac_box[3] * h)
    # square the box around its center using the larger side
    cx, cy = (l + r) / 2, (t + b) / 2
    half = max(r - l, b - t) / 2
    l, t, r, b = cx - half, cy - half, cx + half, cy + half
    # clamp inside the image, preserving size where possible
    if l < 0:
        r -= l; l = 0
    if t < 0:
        b -= t; t = 0
    if r > w:
        l -= r - w; r = w
    if b > h:
        t -= b - h; b = h
    l, t = max(0, l), max(0, t)
    img = img.crop((round(l), round(t), round(r), round(b))).resize((SIZE, SIZE), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=QUALITY, optimize=True)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def discover() -> set:
    """Every photo under households/, as a path relative to households/."""
    found = set()
    for p in HOUSEHOLDS.rglob("*"):
        if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png"}:
            found.add(p.relative_to(HOUSEHOLDS).as_posix())
    return found


def main():
    # A photo with no crop box would otherwise ship as a centre-cropped guess.
    # Warn, don't fail: Tito Boy's folder holds four unused alternates on purpose.
    on_disk = discover()
    used = {rel for rel, _ in FACE_CROPS.values()}
    missing = [rel for rel in used if rel not in on_disk]
    if missing:
        raise SystemExit("FACE_CROPS points at photos that do not exist:\n  " + "\n  ".join(sorted(missing)))
    unused = sorted(on_disk - used)
    if unused:
        print(f"note: {len(unused)} photo(s) in households/ have no FACE_CROPS entry (unused alternates):")
        for rel in unused:
            print(f"  - {rel}")

    entries = []
    total = 0
    for key, (rel, box) in FACE_CROPS.items():
        uri = face_data_uri(HOUSEHOLDS / rel, box)
        total += len(uri)
        entries.append(f"  {key}: '{uri}',")
        print(f"  {key:14s} {len(uri) // 1024:3d} KB  {rel}")
    block = f"{BEGIN}\nconst FACES = {{\n" + "\n".join(entries) + f"\n}};\n{END}"

    html = INDEX.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(html):
        raise SystemExit("FACES markers not found in index.html")
    INDEX.write_text(pattern.sub(lambda _: block, html), encoding="utf-8")
    print(f"Injected {len(FACE_CROPS)} faces, ~{total // 1024} KB total -> {INDEX}")


if __name__ == "__main__":
    main()
